#def trigger_layer_two(device_id: str):
 #   # Stub — replace when Layer 2 is implemented
  #  print(f"[Layer 2 Stub] Would classify audio for device={device_id}")



# -*- coding: utf-8 -*-
"""yamnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmrQdajPBbbEDQlcq5NjoKamhQk8AlcG
"""

!pip install tensorflow_hub resampy
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import csv
import librosa
import matplotlib.pyplot as plt

# Load the YAMNet model from TensorFlow Hub
model = hub.load('https://tfhub.dev/google/yamnet/1')

import tensorflow as tf

# Find the class names
class_map_path = model.class_map_path().numpy()
with tf.io.gfile.GFile(class_map_path) as f:
  class_names = [line.split(',')[1] for line in f.read().splitlines()[1:]]

# Expanded 'Fighting & Conflict' indices
# Includes aggressive vocals + physical impact sounds
SAFETY_INDICES = {
    10: "Yell", 11: "Shouting", 12: "Screaming",
    14: "Crying", 437: "Crash", 441: "Glass", 442: "Shatter",
    434: "Thump", 435: "Bang", 436: "Slap", 438: "Smash"
}
BACKGROUND_INDICES = [0, 66, 508, 494] # Speech, Chatter, TV, HVAC

def analyze_safety(audio_file):
    # Load audio and force 16kHz sample rate
    waveform, sr = librosa.load(audio_file, sr=16000)

    # Normalize the waveform to -1.0 to 1.0 range
    if np.max(np.abs(waveform)) > 0:
        waveform = waveform / np.max(np.abs(waveform))

    # Run the model
    scores, embeddings, spectrogram = model(waveform)
    scores_np = scores.numpy()

    # Use Max scores (Peak detection)
    peak_scores = np.max(scores_np, axis=0)

    print("--- Safety Analysis Results (Enhanced Detection) ---")
    detected_danger = False

    for idx, name in SAFETY_INDICES.items():
        score = peak_scores[idx]

        # DELTA STRATEGY: Detect sudden spikes (rate of change between windows)
        # If the sound increases by > 0.15 suddenly, it's likely an incident
        score_series = scores_np[:, idx]
        max_delta = np.max(np.diff(score_series)) if len(score_series) > 1 else 0

        if score > 0.3 or max_delta > 0.15:
            alert_type = "PEAK" if score > 0.3 else "SUDDEN SPIKE"
            print(f"⚠️ ALERT: {name} detected ({alert_type} Confidence: {int(max(score, max_delta)*100)}%)")
            detected_danger = True

    if not detected_danger:
        highest_danger = max([peak_scores[i] for i in SAFETY_INDICES.keys()])
        safety_conf = max(0, (1.0 - highest_danger) * 100)
        print(f"✅ Environment appears safe ({int(safety_conf)}% confidence).")

    return peak_scores

def smart_alert(peak_scores):
    # Get highest score from your Safety classes
    safety_score = max([peak_scores[i] for i in SAFETY_INDICES.keys()])

    # Revised "Demo-Ready" Logic with lowered thresholds for sensitivity
    if safety_score > 0.15:
        return f"🔴 RED ALERT: Dispatch Staff ({int(safety_score*100)}% Certainty)"
    elif safety_score > 0.10:
        return f"🟡 YELLOW WARNING: Monitor Area ({int(safety_score*100)}% Certainty)"
    else:
        # Express safety as the inverse of danger
        safety_conf = (1.0 - safety_score) * 100
        return f"🟢 GREEN: Normal Activity ({int(safety_conf)}% Confidence)"

def dynamic_vibe_check(audio_file):
    # Load and run model
    waveform, _ = librosa.load(audio_file, sr=16000)
    if np.max(np.abs(waveform)) > 0:
        waveform = waveform / np.max(np.abs(waveform))
    scores, _, _ = model(waveform)

    # Get the top 3 safety classes found in the clip
    safety_results = {SAFETY_INDICES[i]: np.max(scores[:, i]) for i in SAFETY_INDICES.keys()}
    sorted_results = sorted(safety_results.items(), key=lambda x: x[1], reverse=True)

    print("🔎 ENVIRONMENTAL SCAN:")
    for sound, confidence in sorted_results[:3]:
        if confidence > 0.05: # Lowered for demo sensitivity
            color = "🔴" if confidence > 0.3 else "🟡"
            print(f"{color} {sound}: {int(confidence*100)}% certainty")

    # The "Winner" logic for the Map
    top_sound, top_conf = sorted_results[0]
    if top_conf > 0.15:
        return f"ALARM: {top_sound} in progress."
    return "STATUS: Normal"

def plot_spectrogram(audio_file):
    waveform, _ = librosa.load(audio_file, sr=16000)
    _, _, spectrogram = model(waveform)

    plt.figure(figsize=(10, 4))
    plt.imshow(tf.transpose(spectrogram), aspect='auto', origin='lower')
    plt.title('Acoustic Signature (Privacy-Preserving View)')
    plt.ylabel('Frequency Bin')
    plt.xlabel('Time (Frames)')
    plt.colorbar(label='Log Mel-Energy')
    plt.show()

"""# Demo Audio Testing Code"""

from IPython.display import display, Javascript
from google.colab import output
import base64

RECORD_JS = """
const sleep  = time => new Promise(resolve => setTimeout(resolve, time));
const b2text = b => new Promise(resolve => {
  const reader = new FileReader();
  reader.onloadend = e => resolve(e.target.result);
  reader.readAsDataURL(b);
});

async function record(seconds) {
  const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
  const recorder = new MediaRecorder(stream);
  const chunks = [];
  recorder.ondataavailable = e => chunks.push(e.data);
  recorder.start();
  await sleep(seconds * 1000);
  recorder.stop();
  return new Promise(resolve => {
    recorder.onstop = async () => {
      const blob = new Blob(chunks);
      const text = await b2text(blob);
      resolve(text);
    };
  });
}
"""

def record_audio(seconds=5, filename='test.wav'):
  display(Javascript(RECORD_JS))
  print(f"Recording for {seconds} seconds...")
  s = output.eval_js(f'record({seconds})')
  b = base64.b64decode(s.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(b)
  print(f"Saved to {filename}")

import time
import datetime
import numpy as np
import librosa

live_incidents = []

def check_explosive_conflict(waveform, scores_matrix):
    """Detects conflict via classification scores AND sudden energy bursts with highly conservative sensitivity."""
    # 1. Classification-based check (YAMNet)
    shout_indices = [10, 11, 12]
    impact_indices = [434, 435, 436, 437, 438, 441, 442]

    # 2. Energy-based check (Delta detection)
    energy = np.array([np.sum(waveform[i:i+2048]**2) for i in range(0, len(waveform), 2048)])
    if len(energy) > 1:
        energy_delta = np.max(np.diff(energy))
        avg_energy = np.mean(energy)
        # HIGHLY CONSERVATIVE VOCAL SENSITIVITY: Raised multiplier to 8.0x
        is_vocal_spike = energy_delta > (avg_energy * 8.0) and avg_energy > 0.0015
        # Physical impact sensitivity remains low
        is_heavy_burst = energy_delta > (avg_energy * 25.0) and avg_energy > 0.005
    else:
        is_vocal_spike = False
        is_heavy_burst = False

    # Scan frames
    for i in range(scores_matrix.shape[0]):
        max_shout = np.max([scores_matrix[i, j] for j in shout_indices])
        max_impact = np.max([scores_matrix[i, j] for j in impact_indices])

        # HIGHLY CONSERVATIVE VOCAL LOGIC: Raised primary threshold to 0.35
        if max_shout > 0.35 or (is_vocal_spike and max_shout > 0.10):
            return True, "Explosive Vocal/Scolding", max(max_shout, 0.5 if is_vocal_spike else 0)

        # IMPACT LOGIC
        if max_impact > 0.65 or (is_heavy_burst and max_impact > 0.35):
            return True, "Sudden Physical Impact", max(max_impact, 0.7 if is_heavy_burst else 0)

    return False, None, 0

def run_watchdog():
    print("🛡️ WATCHDOG ACTIVE: SILENT MONITORING MODE")
    print("Only incidents will be logged to console.")

    try:
        while True:
            record_audio(seconds=4, filename='current_segment.wav')
            y, _ = librosa.load('current_segment.wav', sr=16000)

            if np.max(np.abs(y)) > 0:
                y_norm = y / np.max(np.abs(y))
            else:
                y_norm = y

            scores, _, _ = model(y_norm)
            scores_np = scores.numpy()

            is_danger, sound_type, intensity = check_explosive_conflict(y_norm, scores_np)

            if is_danger:
                print(f"\n🛑 ALERT: {sound_type} detected at {datetime.datetime.now().strftime('%H:%M:%S')} (Intensity: {int(intensity*100)}%)")
                live_incidents.append({'Timestamp': datetime.datetime.now(), 'Type': sound_type, 'Intensity': intensity})
                break

    except KeyboardInterrupt:
        print("\n🛑 Watchdog deactivated.")

run_watchdog()
